#!/usr/bin/env python3
"""Regenerate the paper's tables directly from ralph/results/*.json. Never type a number.

    python3 tooling/gen-table.py --check      # regenerate and diff against writing/tables/*.tex (exit 1 on drift)
    python3 tooling/gen-table.py --write      # regenerate and overwrite
    python3 tooling/gen-table.py <name>       # print one table to stdout

Spec: writing/tables/spec.json
{
  "tables": [
    {
      "name": "main_table",                        -> writing/tables/main_table.tex
      "src": "s1__run_v1.json",
      "caption": "\\textbf{Main comparison.} ...  Best value per column in \\textbf{bold}.",
      "label": "tab:main",
      "star": false,                                  -> table vs table*
      "row_label": "Variant",
      "rows": [ {"label": "Baseline", "job": "baseline_seed42"}, ... ],
      "cols": [ {"label": "PSNR$\\uparrow$", "key": "best.psnr", "fmt": ".2f", "best": "max"},
                {"label": "LPIPS$\\downarrow$", "key": "best.lpips", "fmt": ".3f", "best": "min"} ],
      "ours": "ours_seed42"                           -> optional: that row is labelled last and bold
    }
  ]
}
`key` is a dot path relative to jobs.<job>; a leading "/" makes it absolute in the file
(e.g. "/analysis.analysis_x.decision.result"). Every emitted cell is wrapped in \\phm{}
so verify-phm.py can bind it; run `gen-table.py --spec-entries` to print the phm-spec rows.

RULE 9 (typography is a claim): bold marks the best value in each column, whoever attains
it. There is deliberately no "bold our method" branch.
"""
import json, os, pathlib, sys

PAPER = pathlib.Path(os.environ.get("PAPER", "/home/work/research/paper"))
R = PAPER / "ralph" / "results"
T = PAPER / "writing" / "tables"
SPEC = T / "spec.json"


def get(obj, path):
    for part in path.split("."):
        obj = obj[int(part)] if isinstance(obj, list) else obj[part]
    return obj


def cell_value(data, job, key):
    if key.startswith("/"):
        return get(data, key[1:])
    return get(data["jobs"][job], key)


def render(tbl):
    data = json.load(open(R / tbl["src"]))
    cols = tbl["cols"]
    vals = {}   # (row_idx, col_idx) -> float|None
    for i, row in enumerate(tbl["rows"]):
        for j, col in enumerate(cols):
            try:
                vals[(i, j)] = cell_value(data, row["job"], col["key"])
            except (KeyError, IndexError):
                vals[(i, j)] = None            # absent, never guessed
    best = {}
    for j, col in enumerate(cols):
        xs = [vals[(i, j)] for i in range(len(tbl["rows"])) if isinstance(vals[(i, j)], (int, float))]
        if xs and col.get("best") in ("max", "min"):
            best[j] = max(xs) if col["best"] == "max" else min(xs)
    env = "table*" if tbl.get("star") else "table"
    out = [f"% GENERATED by tooling/gen-table.py from ralph/results/{tbl['src']} - do not edit by hand",
           f"\\begin{{{env}}}[t]", "\\centering", "\\small",
           f"\\caption{{{tbl['caption']}}}", f"\\label{{{tbl['label']}}}",
           "\\begin{tabular}{l" + "c" * len(cols) + "}", "\\toprule",
           f"{tbl.get('row_label', '')} & " + " & ".join(c["label"] for c in cols) + " \\\\", "\\midrule"]
    rows = list(enumerate(tbl["rows"]))
    ours = tbl.get("ours")
    if ours:
        rows.sort(key=lambda ir: ir[1]["job"] == ours)
    for i, row in rows:
        cells = []
        for j, col in enumerate(cols):
            v = vals[(i, j)]
            if v is None:
                cells.append("--")
                continue
            s = format(v, col.get("fmt", "")) if isinstance(v, (int, float)) else str(v)
            s = f"\\phm{{{s}}}"
            if j in best and isinstance(v, (int, float)) and abs(v - best[j]) < 1e-12:
                s = f"\\textbf{{{s}}}"
            cells.append(s)
        label = row["label"]
        if ours and row["job"] == ours:
            if i != rows[0][0]:
                out.append("\\graymidrule")
            label = f"\\textbf{{{label} (Ours)}}"
        out.append(f"{label} & " + " & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}", f"\\end{{{env}}}", ""]
    return "\n".join(out)


def spec_entries(tbl):
    data = json.load(open(R / tbl["src"]))
    ents = []
    for row in tbl["rows"]:
        for col in tbl["cols"]:
            try:
                v = cell_value(data, row["job"], col["key"])
            except (KeyError, IndexError):
                continue
            s = format(v, col.get("fmt", "")) if isinstance(v, (int, float)) else str(v)
            key = col["key"][1:] if col["key"].startswith("/") else f"jobs.{row['job']}.{col['key']}"
            ents.append({"written": s, "src": tbl["src"], "key": key, "only_in": [f"{tbl['name']}.tex"]})
    return ents


def main():
    if not SPEC.exists():
        print("no writing/tables/spec.json — nothing to generate"); return
    spec = json.load(open(SPEC))
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    drift = 0
    if mode == "--spec-entries":
        ents = [e for t in spec["tables"] for e in spec_entries(t)]
        print(json.dumps(ents, indent=1)); return
    for tbl in spec["tables"]:
        tex = render(tbl)
        dest = T / f"{tbl['name']}.tex"
        if mode == "--write":
            dest.write_text(tex); print(f"wrote {dest.relative_to(PAPER)}")
        elif mode == "--check":
            cur = dest.read_text() if dest.exists() else ""
            if cur != tex:
                drift += 1; print(f"DRIFT {dest.relative_to(PAPER)} (run --write)")
            else:
                print(f"ok    {dest.relative_to(PAPER)}")
        elif mode == tbl["name"]:
            print(tex)
    sys.exit(1 if drift else 0)


if __name__ == "__main__":
    main()
