#!/usr/bin/env python3
"""Build ralph/related/INDEX.md (one table per slice) and ralph/related/survey.bib from the
scout slice files ralph/related/[A-F]_*.md.

    python3 tooling/related_index.py

Each slice file holds entries shaped as:
    ### <bibkey>
    - Title: ...
    - Venue: <venue> <year> (Tier 1|Tier 2|preprint|other) — VERIFIED: yes (...) | no
    - Relevance to HVI-CIDNet: ...   (or "How our thesis uses it:" / "What it changes or criticises:")
    ```bibtex ... ```
Duplicate bibkeys across slices keep the first BibTeX block; known aliases are merged.
"""
import os, pathlib, re, sys

PAPER = pathlib.Path(os.environ.get("PAPER", "/home/work/research/paper"))
R = PAPER / "ralph" / "related"
ALIASES = {"hu2023bread": "guo2023bread", "guo2022bread": "guo2023bread",
           "yang2021sparse": "yang2021sgm"}
REL_KEYS = ("Relevance to HVI-CIDNet", "How our thesis uses it", "What it changes or criticises",
            "What it establishes", "Color space / what it does", "One-line idea")

ENTRY_RE = re.compile(r"^### (\S+)\s*$", re.M)
BIB_RE = re.compile(r"```bibtex\s*(.*?)```", re.S)


def parse(path):
    text = path.read_text(encoding="utf-8")
    heads = list(ENTRY_RE.finditer(text))
    out = []
    for i, m in enumerate(heads):
        block = text[m.end(): heads[i + 1].start() if i + 1 < len(heads) else len(text)]
        e = {"key": m.group(1)}
        for line in block.splitlines():
            line = line.strip()
            if line.startswith("- Title:"):
                e["title"] = line.split(":", 1)[1].strip()
            elif line.startswith("- Venue:"):
                v = line.split(":", 1)[1].strip()
                e["venue"] = v.split("—")[0].split(" - VERIFIED")[0].strip()
                e["tier"] = (re.search(r"\((Tier 1|Tier 2|preprint|other)[^)]*\)", v) or [None, "?"])[1]
                e["verified"] = "yes" if re.search(r"VERIFIED:\s*yes", v) else "no"
            else:
                for k in REL_KEYS:
                    if line.startswith(f"- {k}") and "rel" not in e:
                        e["rel"] = line.split(":", 1)[1].strip()
        b = BIB_RE.search(block)
        e["bib"] = b.group(1).strip() if b else ""
        out.append(e)
    return out


def main():
    files = sorted(p for p in R.glob("[A-F]_*.md"))
    if not files:
        sys.exit("no slice files under ralph/related/")
    index, bib, seen = ["# INDEX.md — generated by tooling/related_index.py; edit the slice files, not this\n"], [], {}
    total = ver = 0
    for f in files:
        entries = parse(f)
        index.append(f"\n## {f.stem}  ({len(entries)} entries)\n")
        index.append("| bibkey | venue | tier | verified | relevance |\n|---|---|---|---|---|")
        for e in entries:
            key = ALIASES.get(e["key"], e["key"])
            rel = e.get("rel", "").replace("|", "/")
            rel = rel if len(rel) <= 160 else rel[:157] + "..."
            index.append(f"| `{key}` | {e.get('venue', '?')} | {e.get('tier', '?')} | {e.get('verified', '?')} | {rel} |")
            total += 1; ver += e.get("verified") == "yes"
            if e["bib"] and key not in seen:
                b = re.sub(r"^(@\w+\{)\S+?,", rf"\g<1>{key},", e["bib"], count=1)
                seen[key] = f.stem
                bib.append(f"% from {f.stem}\n{b}\n")
    index.append(f"\n**{total} entries, {ver} verified, {len(seen)} unique BibTeX keys.**\n")
    (R / "INDEX.md").write_text("\n".join(index), encoding="utf-8")
    (R / "survey.bib").write_text(
        "% survey.bib — generated by tooling/related_index.py from the Phase 0 literature scout.\n"
        "% UNVERIFIED by writing's bibtex pass until merged into custom.bib (harness/writing.md §4c).\n\n"
        + "\n".join(bib), encoding="utf-8")
    print(f"INDEX.md: {total} entries ({ver} verified); survey.bib: {len(seen)} keys")


if __name__ == "__main__":
    main()
